import {
  AgentDescriptorSchema,
  type AgentDescriptor,
  type AgentId,
} from "./contracts.ts";

function agent(
  descriptor: AgentDescriptor,
): AgentDescriptor {
  return AgentDescriptorSchema.parse(descriptor);
}

const referenceHooks = ["builtin.untrusted-content"];
const writerHooks = [
  "builtin.untrusted-content",
  "builtin.write-scope",
  "builtin.command-policy",
];
const stateHooks = ["builtin.state-transition", "builtin.untrusted-content"];

const DESCRIPTORS: Readonly<Record<AgentId, AgentDescriptor>> = {
  "workflow-orchestrator": agent({
    id: "workflow-orchestrator",
    name: "Workflow Orchestrator",
    group: "orchestration",
    purpose: "Select the next legal workflow stage, dispatch bounded agents, and preserve session invariants.",
    modelClass: "coordinator",
    toolProfile: "orchestration-control",
    writesProject: false,
    contextInputs: ["session-state", "workflow-graph", "approval-records"],
    outputArtifact: "dispatch-plan",
    concurrency: "serial",
    requiredHooks: stateHooks,
    maxTurns: 40,
    canDelegate: true,
  }),
  "context-curator": agent({
    id: "context-curator",
    name: "Context Curator",
    group: "orchestration",
    purpose: "Build minimal portable context packets from evidence and approved artifacts without conversation history.",
    modelClass: "fast-text",
    toolProfile: "evidence-read",
    writesProject: false,
    contextInputs: ["evidence-index", "component-spec", "agent-descriptor"],
    outputArtifact: "context-packet",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 20,
    canDelegate: false,
  }),
  "recovery-agent": agent({
    id: "recovery-agent",
    name: "Recovery Agent",
    group: "orchestration",
    purpose: "Reconcile interrupted runs, incomplete artifacts, stale leases, and resumable workflow state.",
    modelClass: "verifier",
    toolProfile: "orchestration-control",
    writesProject: false,
    contextInputs: ["session-state", "audit-log", "artifact-index"],
    outputArtifact: "recovery-report",
    concurrency: "serial",
    requiredHooks: stateHooks,
    maxTurns: 30,
    canDelegate: false,
  }),
  "project-cartographer": agent({
    id: "project-cartographer",
    name: "Project Cartographer",
    group: "discovery",
    purpose: "Map target repository architecture, conventions, entrypoints, tests, and component boundaries.",
    modelClass: "fast-text",
    toolProfile: "project-inspection",
    writesProject: false,
    contextInputs: ["project-profile", "project-file-index"],
    outputArtifact: "project-map",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 25,
    canDelegate: false,
  }),
  "reference-scout": agent({
    id: "reference-scout",
    name: "Reference Scout",
    group: "discovery",
    purpose: "Map authorized reference pages, routes, viewport states, and observable interaction surfaces.",
    modelClass: "vision",
    toolProfile: "browser-observe",
    writesProject: false,
    contextInputs: ["reference-authorization", "browser-evidence"],
    outputArtifact: "reference-map",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 30,
    canDelegate: false,
  }),
  "dom-forensics": agent({
    id: "dom-forensics",
    name: "DOM Forensics",
    group: "discovery",
    purpose: "Extract DOM structure, computed styles, geometry, semantics, and stable selector evidence.",
    modelClass: "fast-text",
    toolProfile: "browser-observe",
    writesProject: false,
    contextInputs: ["dom-evidence", "network-evidence"],
    outputArtifact: "dom-forensics-report",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 25,
    canDelegate: false,
  }),
  "responsive-analyst": agent({
    id: "responsive-analyst",
    name: "Responsive Analyst",
    group: "discovery",
    purpose: "Compare viewport evidence and identify responsive transformations, breakpoints, and visibility changes.",
    modelClass: "vision-reasoning",
    toolProfile: "design-analysis",
    writesProject: false,
    contextInputs: ["desktop-dom", "mobile-dom", "desktop-screenshot", "mobile-screenshot"],
    outputArtifact: "responsive-analysis",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 30,
    canDelegate: false,
  }),
  "interaction-archaeologist": agent({
    id: "interaction-archaeologist",
    name: "Interaction Archaeologist",
    group: "discovery",
    purpose: "Observe keyboard, pointer, focus, scroll, overlay, and browser navigation behavior.",
    modelClass: "vision-reasoning",
    toolProfile: "browser-observe",
    writesProject: false,
    contextInputs: ["interaction-trace", "accessibility-tree", "browser-evidence"],
    outputArtifact: "interaction-contract-draft",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
  "asset-investigator": agent({
    id: "asset-investigator",
    name: "Asset Investigator",
    group: "discovery",
    purpose: "Classify observed fonts, icons, images, and media while preserving provenance and usage restrictions.",
    modelClass: "vision",
    toolProfile: "evidence-read",
    writesProject: false,
    contextInputs: ["network-evidence", "asset-index", "provenance-records"],
    outputArtifact: "asset-provenance-report",
    concurrency: "parallel-readonly",
    requiredHooks: ["builtin.untrusted-content", "builtin.asset-provenance"],
    maxTurns: 25,
    canDelegate: false,
  }),
  "design-dna-extractor": agent({
    id: "design-dna-extractor",
    name: "Design DNA Extractor",
    group: "design",
    purpose: "Synthesize observed visual tokens, layout systems, hierarchy, rhythm, and responsive rules.",
    modelClass: "vision-reasoning",
    toolProfile: "design-analysis",
    writesProject: false,
    contextInputs: ["dom-evidence", "visual-evidence", "responsive-analysis"],
    outputArtifact: "design-dna",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
  "brand-interpreter": agent({
    id: "brand-interpreter",
    name: "Brand Interpreter",
    group: "design",
    purpose: "Map reference design direction to the target brand tokens, content, assets, language, and identity rules.",
    modelClass: "vision-reasoning",
    toolProfile: "design-analysis",
    writesProject: false,
    contextInputs: ["design-dna", "brand-profile", "project-map"],
    outputArtifact: "brand-mapping-plan",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
  "component-architect": agent({
    id: "component-architect",
    name: "Component Architect",
    group: "design",
    purpose: "Convert page decomposition and design evidence into modular component contracts and target file scopes.",
    modelClass: "code",
    toolProfile: "design-analysis",
    writesProject: false,
    contextInputs: ["page-decomposition", "design-dna", "project-map"],
    outputArtifact: "component-spec",
    concurrency: "serial",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
  "motion-analyst": agent({
    id: "motion-analyst",
    name: "Motion Analyst",
    group: "design",
    purpose: "Describe timing, easing, sequencing, reduced-motion behavior, and motion hierarchy from evidence.",
    modelClass: "vision-reasoning",
    toolProfile: "design-analysis",
    writesProject: false,
    contextInputs: ["interaction-trace", "visual-evidence", "design-dna"],
    outputArtifact: "motion-contract",
    concurrency: "parallel-readonly",
    requiredHooks: referenceHooks,
    maxTurns: 30,
    canDelegate: false,
  }),
  "component-builder": agent({
    id: "component-builder",
    name: "Component Builder",
    group: "implementation",
    purpose: "Implement the approved component structure and styling inside the declared target file scope.",
    modelClass: "code",
    toolProfile: "scoped-builder",
    writesProject: true,
    contextInputs: ["component-spec", "project-map", "design-dna", "brand-mapping-plan"],
    outputArtifact: "component-implementation",
    concurrency: "exclusive-write",
    requiredHooks: writerHooks,
    maxTurns: 60,
    canDelegate: false,
  }),
  "responsive-builder": agent({
    id: "responsive-builder",
    name: "Responsive Builder",
    group: "implementation",
    purpose: "Implement the approved responsive transformations and viewport-specific layout behavior.",
    modelClass: "code",
    toolProfile: "scoped-builder",
    writesProject: true,
    contextInputs: ["component-spec", "responsive-analysis", "component-implementation"],
    outputArtifact: "responsive-implementation",
    concurrency: "exclusive-write",
    requiredHooks: writerHooks,
    maxTurns: 50,
    canDelegate: false,
  }),
  "interaction-builder": agent({
    id: "interaction-builder",
    name: "Interaction Builder",
    group: "implementation",
    purpose: "Implement approved interaction states, focus behavior, keyboard handling, and pointer behavior.",
    modelClass: "code",
    toolProfile: "scoped-builder",
    writesProject: true,
    contextInputs: ["component-spec", "interaction-contract-draft", "component-implementation"],
    outputArtifact: "interaction-implementation",
    concurrency: "exclusive-write",
    requiredHooks: writerHooks,
    maxTurns: 50,
    canDelegate: false,
  }),
  "test-builder": agent({
    id: "test-builder",
    name: "Test Builder",
    group: "implementation",
    purpose: "Write deterministic unit, interaction, accessibility, and responsive regression tests for the active component.",
    modelClass: "code",
    toolProfile: "scoped-builder",
    writesProject: true,
    contextInputs: ["component-spec", "acceptance-criteria", "component-implementation"],
    outputArtifact: "component-test-suite",
    concurrency: "exclusive-write",
    requiredHooks: writerHooks,
    maxTurns: 55,
    canDelegate: false,
  }),
  "page-integrator": agent({
    id: "page-integrator",
    name: "Page Integrator",
    group: "implementation",
    purpose: "Integrate approved locked components into the target page while preserving routing and existing behavior.",
    modelClass: "code",
    toolProfile: "scoped-builder",
    writesProject: true,
    contextInputs: ["locked-components", "project-map", "page-decomposition"],
    outputArtifact: "page-integration",
    concurrency: "exclusive-write",
    requiredHooks: writerHooks,
    maxTurns: 60,
    canDelegate: false,
  }),
  "visual-reviewer": agent({
    id: "visual-reviewer",
    name: "Visual Reviewer",
    group: "review",
    purpose: "Compare reference and target captures for geometry, hierarchy, spacing, typography, and visual weight.",
    modelClass: "vision-reasoning",
    toolProfile: "visual-review",
    writesProject: false,
    contextInputs: ["reference-capture", "target-capture", "component-spec"],
    outputArtifact: "visual-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
  "responsive-reviewer": agent({
    id: "responsive-reviewer",
    name: "Responsive Reviewer",
    group: "review",
    purpose: "Verify target viewport transformations against the approved responsive contract.",
    modelClass: "vision-reasoning",
    toolProfile: "visual-review",
    writesProject: false,
    contextInputs: ["responsive-contract", "target-captures", "reference-captures"],
    outputArtifact: "responsive-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 30,
    canDelegate: false,
  }),
  "interaction-reviewer": agent({
    id: "interaction-reviewer",
    name: "Interaction Reviewer",
    group: "review",
    purpose: "Replay and verify pointer, keyboard, focus, overlay, scroll, and dismissal behavior.",
    modelClass: "verifier",
    toolProfile: "verification",
    writesProject: false,
    contextInputs: ["interaction-contract", "target-trace", "interaction-tests"],
    outputArtifact: "interaction-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
  "accessibility-reviewer": agent({
    id: "accessibility-reviewer",
    name: "Accessibility Reviewer",
    group: "review",
    purpose: "Verify semantics, focus order, accessible names, keyboard access, reduced motion, and touch targets.",
    modelClass: "verifier",
    toolProfile: "verification",
    writesProject: false,
    contextInputs: ["component-spec", "accessibility-tree", "target-tests"],
    outputArtifact: "accessibility-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 30,
    canDelegate: false,
  }),
  "code-architecture-reviewer": agent({
    id: "code-architecture-reviewer",
    name: "Code Architecture Reviewer",
    group: "review",
    purpose: "Review modularity, typing, repository conventions, duplication, file scope, and dependency choices.",
    modelClass: "code",
    toolProfile: "code-review",
    writesProject: false,
    contextInputs: ["component-spec", "project-diff", "test-results"],
    outputArtifact: "code-architecture-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
  "performance-reviewer": agent({
    id: "performance-reviewer",
    name: "Performance Reviewer",
    group: "review",
    purpose: "Check runtime cost, layout instability, asset weight, main-thread work, and unnecessary dependencies.",
    modelClass: "verifier",
    toolProfile: "verification",
    writesProject: false,
    contextInputs: ["performance-evidence", "target-capture", "project-diff"],
    outputArtifact: "performance-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 30,
    canDelegate: false,
  }),
  "taste-director": agent({
    id: "taste-director",
    name: "Taste Director",
    group: "review",
    purpose: "Judge coherence, art direction, visual restraint, brand fit, and signs of mechanical interface generation.",
    modelClass: "vision-reasoning",
    toolProfile: "visual-review",
    writesProject: false,
    contextInputs: ["reference-capture", "target-capture", "design-dna", "brand-mapping-plan"],
    outputArtifact: "taste-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 40,
    canDelegate: false,
  }),
  "adversarial-reviewer": agent({
    id: "adversarial-reviewer",
    name: "Adversarial Reviewer",
    group: "review",
    purpose: "Seek missing evidence, unsupported assumptions, untested states, scope violations, and reasons to reject the result.",
    modelClass: "verifier",
    toolProfile: "verification",
    writesProject: false,
    contextInputs: ["all-reviews", "component-spec", "audit-log", "test-results"],
    outputArtifact: "adversarial-review",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 40,
    canDelegate: false,
  }),
  "regression-guardian": agent({
    id: "regression-guardian",
    name: "Regression Guardian",
    group: "review",
    purpose: "Re-run locked component baselines and detect visual, behavioral, accessibility, or test regressions.",
    modelClass: "verifier",
    toolProfile: "verification",
    writesProject: false,
    contextInputs: ["regression-lock", "target-captures", "test-results", "project-diff"],
    outputArtifact: "regression-report",
    concurrency: "review-fanout",
    requiredHooks: referenceHooks,
    maxTurns: 35,
    canDelegate: false,
  }),
};

export const AGENT_DESCRIPTORS: readonly AgentDescriptor[] = Object.freeze(
  Object.values(DESCRIPTORS),
);
